{"uuid": "273dd905-7bc1-4210-9c4b-d98f0e477a2c", "children": ["cb7fabee-99c2-4487-b3fb-ef5f17eafe6a"], "befores": [{"name": "init_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. \n\n", "trace": "  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/tests/conftest.py\", line 21, in init_driver\n    web_driver = webdriver.Firefox(executable_path='geckodriver')\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py\", line 164, in __init__\n    self.service.start()\n  File \"/home/dmitry/PycharmProjects/djangoProject/simbirSoftTestProject/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1627546914747, "stop": 1627546914759}], "start": 1627546914747, "stop": 1627546914905}